### PR TITLE
Some package fixes :)

### PR DESCRIPTION
**Pull request by mrsimonbennett**
Hope you don't mind but had a quick look and fixed a couple of issues :)

- Followed the correct file name Class = file name
- Fixed namespace
- Added composer.lock don't want to commit that on a library
- Updated the PHP version required to support nullable type 
- Add curl as an extension requirement

### CODE REVIEW

**Comment by jbrooksuk** [comment]
@mrsimonbennett I think the `.vscode` folder should be added to the `.gitignore` too.

**Comment by mrsimonbennett** [comment]
@jbrooksuk I thought that too, But should really be in a global ignore right?

I've removed it for now

**Comment by mrsimonbennett** [comment]
@jbrooksuk I stole some suggestions from https://github.com/laravel/framework/blob/8.x/.gitignore

**Comment by jbrooksuk** [comment]
> @jbrooksuk I thought that too, But should really be in a global ignore right?
> 
> I've removed it for now

Yep, definitely in your global `.gitignore`, but we can fix it ourselves this way :)

**Comment by yongfook** [comment]
Thank you @mrsimonbennett @jbrooksuk 👍

**Pull request merged**
